permalink: /:year-:month-:day/:title
markdown: rdiscount
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Mass-Energy Scale"
id : "79390061007"
description : "Understandable masses and energies and how they relate"
thumb: "thumb.gif"
version: "0.0.8"

ml_url: "//minutelabs.io"
ml_library: "//labs.minutelabs.io/library"
ml_assets: "//labs.minutelabs.io/assets"
library_path: "library-build"

show :
  branding: true
  details: true
  comments: true

